# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Tech Musings
tagline:          'A Tech Blog'
description:      'Collection of thoughts and discoveries made on a Tech journey.'
url:              http://kalkrishnan.github.io
baseurl:          /

author:
  name:           'Kal Krishnan'
  url:

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:          https://github.com/kalkrishnan/kalkrishnan.github.io
